import type { DayPlan, Meal } from "./types";
import { T } from "./i18n";

const DAYS = T.days_of_week;

export const WEEK_PLAN: DayPlan[] = DAYS.map((day) => ({
  day,
  breakfast: [],
  morningSnack: [],
  lunch: [],
  afternoonSnack: [],
  dinner: [],
}));

export const DEFAULT_MEAL_LIBRARY: Meal[] = [
  {
    id: "d85648f7-0d26-4d18-9670-3bda722403a9",
    name: "Salát z červené řepy a balkánským sýrem",
    serves: 1,
    favourite: true,
    mealTypes: ["snack", "dinner"],
    ingredients: [
      { name: "červené řepy", amount: "180", unit: "g" },
      { name: "balkánského sýra", amount: "80", unit: "g" },
      { name: "vlašských ořechů", amount: "20", unit: "g" },
      { name: "cizrny", amount: "50", unit: "g" },
      { name: "olivového oleje", amount: "10", unit: "ml" },
    ],
    procedure: [
      "Červenou řepu uvaříme nebo upečeme doměkka (cca 30–40 min.),\nnecháme vychladnout a nakrájíme na kostky nebo tenké plátky.",
      "Cizrnu scedíme a promícháme s řepou v míse.",
      "Přidáme nakrájený balkánský sýr, vlašské ořechy a cizrnu.",
      "Vše zakápneme olivovým olejem, lehce promícháme a podle chuti\ndochutíme solí, pepřem nebo kapkou balzamikového octa.",
    ],
    macros: { calories: 577, protein: 25, carbohydrates: 29, fat: 39 },
  },
  {
    id: "405d3838-35b1-4bd9-8637-8791c475ec24",
    name: "Tiramisu do skleničky",
    serves: 1,
    favourite: true,
    mealTypes: ["snack"],
    ingredients: [
      { name: "nízkotučného tvarohu nebo řeckého jogurtu", amount: "150", unit: "g" },
      { name: "syrovátkového proteinu", amount: "20", unit: "g" },
      { name: "čekankového sirupu", amount: "10", unit: "ml" },
      { name: "dětských piškotů (nebo piškoty bez cukru)", amount: "30", unit: "g" },
      { name: "kakao, černá káva", amount: "", unit: "" },
    ],
    procedure: [
      "Uvaříme kávu a necháme ji vychladnout.",
      "Smícháme nízkotučný tvaroh nebo řecký jogurt s trochou proteinu.\nMůžeme osladit čekankovým sirupem nebo sladidlem ze stévie.",
      "Piškoty namočíme do kávy, jen na pár sekund, aby se nerozmočily.",
      "Na dno sklenice rozložíme první vrstvu piškotů a naneseme\npolovinu krému.",
      "Přidáme druhou vrstvu piškotů a zbytek krému.",
      "Povrch posypeme kakaem, můžeme přidat i hořkou čokoládu.",
      "Dáme aspoň na 2–3 hodiny, ideálně přes noc, do lednice.",
    ],
    macros: { calories: 326, protein: 38, carbohydrates: 31, fat: 4 },
  },
  {
    id: "d5c9a448-c2b8-4cdf-9f71-6b94b27436c5",
    name: "Ovesné vločky přes noc",
    serves: 1,
    favourite: true,
    mealTypes: ["breakfast"],
    ingredients: [
      { name: "ovesných vloček", amount: "40", unit: "g" },
      { name: "řeckého jogurtu", amount: "100", unit: "g" },
      { name: "syrovátkového proteinu", amount: "15", unit: "g" },
      { name: "banán", amount: "1", unit: "" },
      { name: "hořké čokolády", amount: "15", unit: "g" },
      { name: "ovoce - borůvky, maliny, chia semínka..", amount: "", unit: "" },
    ],
    procedure: [
      "Do sklenice nebo uzavíratelné misky nasypeme ovesné vločky,\nřecký jogurt, protein a nakrájený nebo rozmačkaný banán.",
      " Můžeme přílít trochu mléka pro lepší konzistenci.",
      "Vmícháme chia semínka a nasekanou hořkou čokoládu.",
      "Navrch přidáme ovoce - borůvky maliny nebo polovinu banánu.",
      "Zakryjeme víčkem a necháme odležet přes noc v lednici.",
    ],
    macros: { calories: 440, protein: 29, carbohydrates: 54, fat: 11 },
  },
  {
    id: "9cbbb9a7-74d2-4668-a732-b61ba2c22300",
    name: "Tatranka",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [],
    procedure: [],
    macros: { calories: 240, protein: 3, carbohydrates: 26, fat: 13 },
  },
  {
    id: "93322da7-0606-4561-ac04-7cdb445d1f9b",
    name: "Olivový olej",
    serves: 1,
    ingredients: [
      { name: "Olivový olej", amount: "1", unit: "ml" },
    ],
    procedure: [],
    macros: { calories: 8, protein: 0, carbohydrates: 0, fat: 0 },
  },
  {
    id: "35feb9f5-1900-4e4f-a63d-2fae63cc5c3a",
    name: "Chili con carne s rýží",
    serves: 1,
    favourite: true,
    mealTypes: ["lunch", "dinner"],
    ingredients: [
      { name: "hovězího mletého masa", amount: "170", unit: "g" },
      { name: "olivového oleje", amount: "5", unit: "ml" },
      { name: "červených fazolí", amount: "100", unit: "g" },
      { name: "rýže", amount: "65", unit: "g" },
      { name: "Loupaná rajčata", amount: "", unit: "" },
      { name: "Paprika", amount: "", unit: "" },
      { name: "Kukuřice", amount: "", unit: "" },
    ],
    procedure: [
      "Nejprve dáme vařit rýži podle návodu.",
      "Na pánvi rozehřejeme olivový olej a orestujeme mleté hovězí maso.",
      "Poté přidáme loupaná rajčata, scezené červené fazole a kukuřici.",
      "Vše dochutíme solí, pepřem, česnekem a chilli. Necháme dusit\nzhruba 5 minut, dokud směs nezhoustne a nepropojí se chutě.",
      "Podáváme s porcí uvařené rýže.",
    ],
    macros: { calories: 728, protein: 42, carbohydrates: 69, fat: 26 },
  },
  {
    id: "937f0a14-5bc1-4809-b927-f25e36331992",
    name: "Kuskusové rizoto s kuřecím",
    serves: 1,
    favourite: true,
    mealTypes: ["lunch", "dinner"],
    ingredients: [
      { name: "kuřecích prsou", amount: "180", unit: "g" },
      { name: "Kuskusu", amount: "60", unit: "g" },
      { name: "Olivového oleje", amount: "5", unit: "ml" },
      { name: "zeleninového mixu", amount: "100", unit: "g" },
    ],
    procedure: [
      "Okořeníme maso a dáme péct do fritézy nebo na pánev.",
      "Kuskus nasypeme do hrnce, zalijeme vroucí vodou a přikryjeme\npokličkou.",
      "Zmraženou zeleninu necháme rozmrazit. Jakmile je kuskus hotový,\npromícháme ho se zeleninou přímo v hrnci.",
      "Hotové kuřecí prso nakrájíme na plátky a položíme navrch.",
    ],
    macros: { calories: 534, protein: 54, carbohydrates: 48, fat: 14 },
  },
  {
    id: "c1da3b3d-0924-480a-a1b7-373e8a2c74bf",
    name: "Míchaná vajíčka s žitným chlebem",
    serves: 1,
    favourite: true,
    mealTypes: ["breakfast"],
    ingredients: [
      { name: "Chléb žitný", amount: "70", unit: "g" },
      { name: "Míchaná vajíčka", amount: "3", unit: "ks" },
      { name: "Máslo", amount: "10", unit: "g" },
      { name: "Olivový olej", amount: "5", unit: "ml" },
    ],
    procedure: [
      "Přidám olivový olej na rozehřátou pánev",
      "Do pánve přidám osolená vajíčka a míchám",
      "Na žitný chleba přidám máslo",
      "Vajíčka mohu na talíři opepřit",
    ],
    macros: { calories: 516, protein: 23, carbohydrates: 36, fat: 30 },
  },
  {
    id: "b50f1a09-694f-4136-88c1-e0f06a09e2ec",
    name: "Žitný chléb s mozzarelou a nektarinkou",
    serves: 1,
    favourite: true,
    mealTypes: ["breakfast", "snack"],
    ingredients: [
      { name: "Žitný chléb", amount: "70", unit: "g" },
      { name: "Mozzarella", amount: "1", unit: "ks" },
      { name: "Nektarinka", amount: "1", unit: "ks" },
      { name: "Šunka vepřová", amount: "70", unit: "g" },
    ],
    procedure: [
      "Žitný chléb nakrájíme na plátky.",
      "Na každý plátek položíme plátky mozzarelly a šunky.",
      "Podáváme s nektarinkou nakrájenou na plátky nebo celou.",
    ],
    macros: { calories: 566, protein: 41, carbohydrates: 44, fat: 24 },
  },
  {
    id: "b65f1c80-63b6-4604-a45b-5eeefad383cd",
    name: "Mozzarella",
    serves: 1,
    ingredients: [
      { name: "Mozzarella", amount: "1", unit: "ks" },
    ],
    procedure: [],
    macros: { calories: 273, protein: 21, carbohydrates: 2, fat: 20 },
  },
  {
    id: "615a2d17-ae0f-44d2-8e6c-52b5b7d3a23f",
    name: "Tvaroh tučný",
    serves: 1,
    mealTypes: ["breakfast", "snack"],
    ingredients: [
      { name: "Tvaroh tučný", amount: "1", unit: "ks" },
    ],
    procedure: [],
    macros: { calories: 326, protein: 22, carbohydrates: 8, fat: 22 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000001",
    name: "Máslo",
    serves: 1,
    ingredients: [{ name: "Máslo", amount: "10", unit: "g" }],
    procedure: [],
    macros: { calories: 74, protein: 0, carbohydrates: 0, fat: 8 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000002",
    name: "Vejce",
    serves: 1,
    ingredients: [{ name: "Vejce", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 70, protein: 6, carbohydrates: 0, fat: 5 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000003",
    name: "Řecký jogurt",
    serves: 1,
    mealTypes: ["breakfast", "snack"],
    ingredients: [{ name: "Řecký jogurt", amount: "150", unit: "g" }],
    procedure: [],
    macros: { calories: 80, protein: 14, carbohydrates: 5, fat: 5 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000004",
    name: "Banán",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [{ name: "Banán", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 84, protein: 1, carbohydrates: 23, fat: 0 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000005",
    name: "Jablko",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [{ name: "Jablko", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 72, protein: 0, carbohydrates: 19, fat: 0 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000006",
    name: "Pomeranč",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [{ name: "Pomeranč", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 74, protein: 1, carbohydrates: 15, fat: 0 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000012",
    name: "Nektarinka",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [{ name: "Nektarinka", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 40, protein: 1, carbohydrates: 8, fat: 0 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000020",
    name: "Párek",
    serves: 1,
    mealTypes: ["snack"],
    ingredients: [{ name: "Párek", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 140, protein: 6, carbohydrates: 1, fat: 12 },
  },
  {
    id: "a1b2c3d4-0001-4000-8000-000000000021",
    name: "Rohlík",
    serves: 1,
    mealTypes: ["breakfast", "snack"],
    ingredients: [{ name: "Rohlík", amount: "1", unit: "ks" }],
    procedure: [],
    macros: { calories: 130, protein: 4, carbohydrates: 24, fat: 1 },
  },
];
